@host = http://localhost:5122
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZDU3MzliZC0zYmM0LTRkOTYtODNiOS1mMGU5NjlmYzY1ZDUiLCJlbWFpbCI6ImFheGNjenhAbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6ImFheGNjengiLCJpc19vbmJvYXJkaW5nX2NvbXBsZXRlZCI6IkZhbHNlIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYXBwbGljYW50IiwiZXhwIjoxNzY2OTM3MDY1LCJpc3MiOiJUaGlzQXBwIiwiYXVkIjoiVGhpc0FwcFVzZXJzIn0.P_SMuwYnO-OJ4f6I9HfRiLUVl7vZnueFLf6rlKb40AA


GET {{host}}/notifications/telegram/suscribe
Authorization: Bearer {{user_token}}
