@host = http://localhost:5122

POST {{host}}/auth/signup
Content-Type: application/json

{
    "email": "emailexample@mail.com",
    "password": "StrongP@ssw0rd!",
    "confirmPassword": "StrongP@ssw0rd!",
    "username": "randomuser4",
    "role": "recruiter"
}