
@recruiter_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzNmYjMzMi04NjBhLTRjNGMtYmJjZi03OTk4M2FhODRiMTciLCJlbWFpbCI6ImVtYWlsZXh4YW1wbGVjQG1haWwuY29tIiwianRpIjoiYWJiNDRmOTUtYmJhZi00YTNiLThjNGUtOTY4MDZiNTIyZDc2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoicmVjcnVpdGVyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imxlb3p6YW5yZG9mMDIiLCJvbmJvYXJkaW5nX2NvbXBsZXRlZCI6ImZhbHNlIiwiZXhwIjoxNzY2Njg5NDA3LCJpc3MiOiJUaGlzQXBwIiwiYXVkIjoiVGhpc0FwcFVzZXJzIn0.LuCyjVIAneByYg2qsr4ftj_RJUqTeZuv0fnpsPGZcfI
@host = http://localhost:5122

POST {{host}}/auth/login
Content-Type: application/json
Authorization: Bearer {{recruiter_token}}

{
    "fullName": "Leozz Andre",
    "profileTitle": "Senior Recruiter"
}