@applicant_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmZmMDM4OS1kZTQ3LTQ4MDAtYjUzZC0yZjI0ZGFlZmE2YTAiLCJlbWFpbCI6ImFheGNjenhAbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6ImFheGNjengiLCJpc19vbmJvYXJkaW5nX2NvbXBsZXRlZCI6IlRydWUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhcHBsaWNhbnQiLCJleHAiOjE3NjY4NjQ3MjIsImlzcyI6IlRoaXNBcHAiLCJhdWQiOiJUaGlzQXBwVXNlcnMifQ.EV17GFiekcVfdAwwttC2VonuhuWZKaCbUNlC8Nt2UpQ
@host = http://localhost:5122

POST {{host}}/joboffers/1/applications
Authorization: Bearer {{applicant_token}}